/* ARJONA +AI STUDIO — COMPLETE JS WITH MOBILE LIGHTROOM LAYOUT */

/* ===== AI CHAT ===== */
var aiChatOpen = false, ttsOn = false, lastActionTime = Date.now();
var aiChatMem = [];
try { aiChatMem = JSON.parse(localStorage.getItem('ai_chat_mem') || '[]'); } catch (e) { aiChatMem = []; }

function toggleAiChat() { var box = document.getElementById('aiChatBox'); aiChatOpen = !aiChatOpen; if (aiChatOpen) box.classList.remove('hidden'); else box.classList.add('hidden'); }

function getCanvasContext() { var texts = [], imgC = 0, selInfo = 'none'; for (var i = 0; i < els.length; i++) { if (els[i].type === 'text') texts.push(els[i].text || ''); if (els[i].type === 'image') imgC++; } if (selId) { var sel = findEl(selId); if (sel) selInfo = sel.type === 'text' ? 'text:"' + (sel.text || '') + '"' : 'image'; } return 'Canvas:' + canvas.width + 'x' + canvas.height + ',' + els.length + ' elements,' + imgC + ' images,texts:[' + texts.join(',') + '],selected:' + selInfo; }

function addAiMem(role, text) { aiChatMem.push({ role: role, text: text, t: Date.now() }); if (aiChatMem.length > 10) aiChatMem = aiChatMem.slice(-10); try { localStorage.setItem('ai_chat_mem', JSON.stringify(aiChatMem)); } catch (e) { } lastActionTime = Date.now(); }

function addChatMsg(text, isBot) { var body = document.getElementById('aiChatBody'); if (!body) return; var div = document.createElement('div'); div.className = 'ai-msg ' + (isBot ? 'ai-msg-bot' : 'ai-msg-user'); div.innerText = text; body.appendChild(div); body.scrollTop = body.scrollHeight; }

function showTyping(show) { var el = document.getElementById('aiTyping'); if (el) el.style.display = show ? 'block' : 'none'; }

function askAI(context, showInChat) { if (showInChat !== false) addAiMem('system', context); var memStr = ''; for (var i = 0; i < aiChatMem.length; i++)memStr += aiChatMem[i].role + ': ' + aiChatMem[i].text + '\n'; var prompt = 'You are Arjona AI, funny Hinglish design buddy. Max 20 words. Context: ' + getCanvasContext() + '. History:\n' + memStr + '\nUser: ' + context + '. Reply:'; showTyping(true); fetch('https://text.pollinations.ai/' + encodeURIComponent(prompt)).then(function (r) { return r.text(); }).then(function (text) { showTyping(false); text = (text || '').trim().substring(0, 120); if (!text || text.length < 2) text = 'Mast kaam boss!'; if (showInChat !== false) { addChatMsg(text, true); addAiMem('bot', text); } updateLog(text); if (ttsOn) speakTTS(text); }).catch(function () { showTyping(false); var fb = ['Design solid hai!', 'Boss mode!', 'Mast!', 'Zabardast!']; var t = fb[Math.floor(Math.random() * fb.length)]; if (showInChat !== false) addChatMsg(t, true); updateLog(t); }); }

function sendAiChat() { var inp = document.getElementById('aiChatInput'); var msg = (inp.value || '').trim(); inp.value = ''; if (!msg) return; addChatMsg(msg, false); addAiMem('user', msg); var low = msg.toLowerCase(); if (low.indexOf('add text') >= 0) { addText(); askAI('user asked to add text'); } else if (low.indexOf('gray') >= 0) { grayscale(); askAI('applied grayscale'); } else if (low.indexOf('blur') >= 0) { applyBlur(4); askAI('applied blur'); } else if (low.indexOf('invert') >= 0) { invertColors(); askAI('inverted colors'); } else if (low.indexOf('pixel') >= 0) { pixelate(10); askAI('pixelated'); } else if (low.indexOf('export') >= 0) { exportHD(); askAI('exported PNG'); } else if (low.indexOf('undo') >= 0) { triggerUndo(); askAI('undone'); } else if (low.indexOf('remove bg') >= 0 || low.indexOf('background') >= 0) { bgRemove('smart'); askAI('bg remove'); } else if (low.indexOf('center') >= 0) { alignEl('c'); askAI('centered'); } else if (low.indexOf('delete') >= 0) { layerOp('del'); askAI('deleted'); } else { askAI('user says: ' + msg); } }

function startAiVoice() { var SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) { alert('Speech not supported'); return; } var rec = new SR(); rec.lang = 'en-US'; var btn = document.getElementById('aiVoiceBtn'); if (btn) btn.innerText = '...'; rec.onresult = function (e) { var t = e.results[0][0].transcript; document.getElementById('aiChatInput').value = t; sendAiChat(); }; rec.onend = function () { if (btn) btn.innerText = 'Mic'; }; rec.onerror = function () { if (btn) btn.innerText = 'Mic'; }; rec.start(); }

function speakTTS(text) { if (!('speechSynthesis' in window)) return; try { speechSynthesis.cancel(); } catch (e) { } var u = new SpeechSynthesisUtterance(text); u.lang = 'hi-IN'; u.rate = 1.1; u.volume = 0.7; try { speechSynthesis.speak(u); } catch (e) { } }

function toggleTTS() { ttsOn = !ttsOn; var btn = document.getElementById('ttsBtn'); if (btn) btn.innerText = ttsOn ? 'Voice On' : 'Voice Off'; }

function react(k) { askAI(k, false); }

function updateLog(text) { var l1 = document.getElementById('logTxt'), l2 = document.getElementById('logTxt2'); if (l1) l1.innerText = text; if (l2) l2.innerText = text; }

setInterval(function () { if (Date.now() - lastActionTime > 20000) { askAI('user idle, suggest design tip', false); lastActionTime = Date.now(); } }, 15000);

/* ===== THEME ===== */
function toggleTheme() { var h = document.documentElement; var n = h.getAttribute('data-theme') === 'dark' ? 'light' : 'dark'; h.setAttribute('data-theme', n); var btn = document.getElementById('themeToggle'); if (btn) btn.innerText = n === 'dark' ? 'Night' : 'Day'; try { localStorage.setItem('ds_theme', n); } catch (e) { } }

function initTheme() { var saved = null; try { saved = localStorage.getItem('ds_theme'); } catch (e) { } if (!saved && window.matchMedia && window.matchMedia('(prefers-color-scheme:light)').matches) saved = 'light'; if (saved) { document.documentElement.setAttribute('data-theme', saved); var btn = document.getElementById('themeToggle'); if (btn) btn.innerText = saved === 'dark' ? 'Night' : 'Day'; } }

/* ===== MODALS ===== */
function openHelp() { document.getElementById('helpModal').style.display = 'flex'; }
function closeHelp() { document.getElementById('helpModal').style.display = 'none'; }

/* ===== MOBILE MENU ===== */
function toggleMobMenu() { var d = document.getElementById('mobMenuDrawer'); var o = document.getElementById('mobMenuOverlay'); if (d.classList.contains('open')) { d.classList.remove('open'); o.classList.remove('open'); } else { d.classList.add('open'); o.classList.add('open'); } }
function closeMobMenu() { document.getElementById('mobMenuDrawer').classList.remove('open'); document.getElementById('mobMenuOverlay').classList.remove('open'); }

/* ===== MOBILE BOTTOM SHEETS ===== */
var currentSheet = null;
var sheetDragStartY = 0, sheetStartBottom = 0, sheetDragging = false;

function openBottomSheet(btn, sheetId) {
    var btns = document.querySelectorAll('.mob-bar-btn'); for (var i = 0; i < btns.length; i++)btns[i].classList.remove('active');
    btn.classList.add('active');
    var sheets = document.querySelectorAll('.mob-sheet'); for (var i = 0; i < sheets.length; i++)sheets[i].classList.remove('open');
    var overlay = document.getElementById('mobSheetOverlay');
    if (currentSheet === sheetId) { currentSheet = null; overlay.classList.remove('open'); return; }
    var sheet = document.getElementById(sheetId); if (sheet) { sheet.classList.add('open'); overlay.classList.add('open'); currentSheet = sheetId; }
}

function closeBottomSheet() {
    var sheets = document.querySelectorAll('.mob-sheet'); for (var i = 0; i < sheets.length; i++)sheets[i].classList.remove('open');
    document.getElementById('mobSheetOverlay').classList.remove('open');
    currentSheet = null;
    var btns = document.querySelectorAll('.mob-bar-btn'); for (var i = 0; i < btns.length; i++)btns[i].classList.remove('active');
}

function sheetDragStart(e) { sheetDragging = true; sheetDragStartY = e.touches[0].clientY; }
function sheetDragMove(e) { if (!sheetDragging) return; var dy = e.touches[0].clientY - sheetDragStartY; if (dy > 60) closeBottomSheet(); }
function sheetDragEnd(e) { sheetDragging = false; }

/* ===== MOBILE AI GENERATE ===== */
function generateAIMobile() {
    var prompt = document.getElementById('mobAiPrompt').value.trim(); if (!prompt) { return; }
    var style = document.getElementById('mobAiStyle').value || '';
    var el = document.getElementById('aiPrompt'); if (el) el.value = prompt;
    var stEl = document.getElementById('aiStyle'); if (stEl) stEl.value = style;
    var modeEl = document.getElementById('aiMode'); if (modeEl) modeEl.value = 'bg';
    generateAI();
}

/* ===== RESIZE PANELS ===== */
var resLOn = false, resLX = 0, resLW = 0, resBOn = false, resBY = 0, resBH = 0;

/* ===== CORNER RESIZE ===== */
var cornerDrag = null, cornerStartX = 0, cornerStartY = 0, cornerStartScale = 100;

function findEl(id) { for (var i = 0; i < els.length; i++) { if (els[i].id === id) return els[i]; } return null; }

function showCornerHandles(el) {
    var ids = ['rhNW', 'rhNE', 'rhSW', 'rhSE'];
    if (!el) { for (var i = 0; i < ids.length; i++) { var h = document.getElementById(ids[i]); if (h) h.style.display = 'none'; } return; }
    var cr = canvas.getBoundingClientRect(), sx = cr.width / canvas.width, sy = cr.height / canvas.height;
    var ex, ey, ew, eh;
    if (el.type === 'image') { ew = el.content.width * (el.scale / 100); eh = el.content.height * (el.scale / 100); ex = el.x; ey = el.y; }
    else { ctx.save(); ctx.font = 'bold ' + (el.scale * 0.6) + 'px "' + el.font + '"'; var tw = ctx.measureText(el.text || '').width; ctx.restore(); ew = tw + 20; eh = el.scale * 0.8; ex = el.x - ew / 2; ey = el.y - eh / 2; }
    var px = cr.left + ex * sx, py = cr.top + ey * sy, pw = ew * sx, ph = eh * sy;
    var pos = [[px - 6, py - 6], [px + pw - 6, py - 6], [px - 6, py + ph - 6], [px + pw - 6, py + ph - 6]];
    for (var i = 0; i < ids.length; i++) { var h = document.getElementById(ids[i]); if (h) { h.style.left = pos[i][0] + 'px'; h.style.top = pos[i][1] + 'px'; h.style.display = 'block'; } }
}

function hideCornerHandles() { var ids = ['rhNW', 'rhNE', 'rhSW', 'rhSE']; for (var i = 0; i < ids.length; i++) { var h = document.getElementById(ids[i]); if (h) h.style.display = 'none'; } }

function initCornerResize(id, e) { var el = findEl(selId); if (!el) return; if (e.preventDefault) e.preventDefault(); if (e.stopPropagation) e.stopPropagation(); cornerDrag = id; cornerStartX = e.clientX; cornerStartY = e.clientY; cornerStartScale = el.scale; document.body.style.userSelect = 'none'; }

/* ===== SPACE BG ===== */
var bgC = document.getElementById('bgCanvas'), bgX = bgC.getContext('2d'), strs = [], shts = [], nP = 0;
function iBg() { bgC.width = innerWidth; bgC.height = innerHeight; strs = []; for (var i = 0; i < 80; i++)strs.push({ x: Math.random() * bgC.width, y: Math.random() * bgC.height, s: Math.random() * 1.2 + .3, o: Math.random(), d: Math.random() * .01 + .002, c: Math.random() > .75 }); }
function bF() { nP += .003; bgX.fillStyle = '#020206'; bgX.fillRect(0, 0, bgC.width, bgC.height); var nx = bgC.width / 2 + Math.cos(nP) * 60, ny = bgC.height * .35 + Math.sin(nP * .7) * 30, nr = Math.max(bgC.width * .3, 250); var ng = bgX.createRadialGradient(nx, ny, 10, nx, ny, nr); ng.addColorStop(0, 'rgba(124,58,237,.08)'); ng.addColorStop(.3, 'rgba(0,242,254,.03)'); ng.addColorStop(1, 'rgba(0,0,0,0)'); bgX.fillStyle = ng; bgX.fillRect(0, 0, bgC.width, bgC.height); for (var i = 0; i < strs.length; i++) { var s = strs[i]; s.o += s.d; if (s.o > 1 || s.o < 0) s.d = -s.d; bgX.fillStyle = 'rgba(' + (s.c ? '124,58,237' : '0,242,254') + ',' + Math.max(0, Math.min(1, s.o)) + ')'; bgX.beginPath(); bgX.arc(s.x, s.y, s.s, 0, Math.PI * 2); bgX.fill(); } if (shts.length < 2 && Math.random() < .005) shts.push({ x: Math.random() * bgC.width * .7, y: -10, l: Math.random() * 60 + 30, o: 1, dx: Math.random() * 3 + 2, dy: Math.random() * 2 + 2 }); for (var i = shts.length - 1; i >= 0; i--) { var p = shts[i]; p.x += p.dx; p.y += p.dy; p.o -= .011; if (p.o <= 0 || p.x > bgC.width || p.y > bgC.height) { shts.splice(i, 1); continue; } var t = p.dx + p.dy, tx = p.x - p.l * (p.dx / t), ty = p.y - p.l * (p.dy / t); var sg = bgX.createLinearGradient(p.x, p.y, tx, ty); sg.addColorStop(0, 'rgba(255,255,255,' + p.o + ')'); sg.addColorStop(.3, 'rgba(0,242,254,' + p.o * .6 + ')'); sg.addColorStop(1, 'rgba(124,58,237,0)'); bgX.save(); bgX.strokeStyle = sg; bgX.lineWidth = 1.5; bgX.lineCap = 'round'; bgX.shadowColor = '#00f2fe'; bgX.shadowBlur = 5; bgX.beginPath(); bgX.moveTo(p.x, p.y); bgX.lineTo(tx, ty); bgX.stroke(); bgX.restore(); } requestAnimationFrame(bF); }
window.addEventListener('resize', function () { iBg(); R(); }); iBg(); bF();

/* ===== STATE ===== */
var canvas = document.getElementById('mainCanvas'), ctx = canvas.getContext('2d'), loader = document.getElementById('loader');
var els = [], selId = null, aiBg = null, bgCf = null, uS = [], rS = [], mode = 'select', bSz = 25, drag = false, dX = 0, dY = 0;

/* ===== TABS ===== */
function bpTab(btn) { var ts = document.querySelectorAll('.bp-tab'), ps = document.querySelectorAll('.bp-pan'); for (var i = 0; i < ts.length; i++)ts[i].classList.remove('active'); for (var i = 0; i < ps.length; i++)ps[i].classList.remove('active'); btn.classList.add('active'); var p = document.getElementById(btn.getAttribute('data-p')); if (p) p.classList.add('active'); }
function bgT(btn) { var ts = document.querySelectorAll('.bgt'), ps = document.querySelectorAll('.bgp'); for (var i = 0; i < ts.length; i++)ts[i].classList.remove('active'); for (var i = 0; i < ps.length; i++)ps[i].classList.remove('active'); btn.classList.add('active'); var p = document.getElementById(btn.getAttribute('data-p')); if (p) p.classList.add('active'); }

/* ===== SEL BAR ===== */
function showSelBar(el) { var bar = document.getElementById('selBar'), df = document.getElementById('delFloat'); if (!el) { bar.style.display = 'none'; df.style.display = 'none'; hideCornerHandles(); return; } var r = canvas.getBoundingClientRect(), bx, by; if (el.type === 'image') { var w = el.content.width * (el.scale / 100); bx = r.left + el.x * (r.width / canvas.width) + w * (r.width / canvas.width) / 2; by = r.top + el.y * (r.height / canvas.height) - 22; } else { bx = r.left + el.x * (r.width / canvas.width); by = r.top + el.y * (r.height / canvas.height) - el.scale * .25 * (r.height / canvas.height) - 22; } bar.style.left = Math.max(3, Math.min(innerWidth - 170, bx - 75)) + 'px'; bar.style.top = Math.max(44, by) + 'px'; bar.style.display = 'flex'; df.style.display = 'block'; showCornerHandles(el); }

/* ===== CANVAS ===== */
function setupC(w, h) { canvas.width = w; canvas.height = h; var info = document.getElementById('cvInfo'); if (info) info.innerText = w + ' x ' + h; R(); }

/* ===== BG ===== */
function setBg(type, sub) { if (type === 'solid') { var c = document.getElementById('bgSC'); var mc = document.getElementById('mobBgSC'); bgCf = { type: 'solid', color: (c ? c.value : '#0a0f1e') }; } else if (type === 'grad') bgCf = { type: 'grad', c1: document.getElementById('bgG1').value, c2: document.getElementById('bgG2').value, dir: document.getElementById('bgGD').value }; else if (type === 'pat') bgCf = { type: 'pat', pat: sub, pc: document.getElementById('bgPC').value, bc: document.getElementById('bgPB').value }; aiBg = null; sH(); R(); react('bg changed'); }
function preBg(c1, c2) { bgCf = c1 === c2 ? { type: 'solid', color: c1 } : { type: 'grad', c1: c1, c2: c2, dir: 'diag' }; aiBg = null; sH(); R(); react('preset bg'); }
function clearBg() { bgCf = null; aiBg = null; sH(); R(); }
function paintBg() { var W = canvas.width, H = canvas.height; if (aiBg && aiBg.complete && aiBg.naturalWidth > 0) { var s = Math.max(W / aiBg.naturalWidth, H / aiBg.naturalHeight); ctx.drawImage(aiBg, (W - aiBg.naturalWidth * s) / 2, (H - aiBg.naturalHeight * s) / 2, aiBg.naturalWidth * s, aiBg.naturalHeight * s); return; } if (!bgCf) { var g = ctx.createLinearGradient(0, 0, W, H); g.addColorStop(0, '#090f1d'); g.addColorStop(.5, '#0c1a2e'); g.addColorStop(1, '#060b16'); ctx.fillStyle = g; ctx.fillRect(0, 0, W, H); return; } var c = bgCf; if (c.type === 'solid') { ctx.fillStyle = c.color; ctx.fillRect(0, 0, W, H); } else if (c.type === 'grad') { var g; if (c.dir === 'rad') g = ctx.createRadialGradient(W / 2, H / 2, 0, W / 2, H / 2, Math.max(W, H) / 2); else if (c.dir === 'lr') g = ctx.createLinearGradient(0, 0, W, 0); else if (c.dir === 'diag') g = ctx.createLinearGradient(0, 0, W, H); else g = ctx.createLinearGradient(0, 0, 0, H); g.addColorStop(0, c.c1); g.addColorStop(1, c.c2); ctx.fillStyle = g; ctx.fillRect(0, 0, W, H); } else if (c.type === 'pat') { ctx.fillStyle = c.bc || '#0a0f1e'; ctx.fillRect(0, 0, W, H); ctx.save(); ctx.strokeStyle = c.pc || '#00f2fe'; ctx.fillStyle = c.pc || '#00f2fe'; ctx.globalAlpha = .12; var sz = 24; if (c.pat === 'dots') { for (var x = 0; x < W; x += sz)for (var y = 0; y < H; y += sz) { ctx.beginPath(); ctx.arc(x, y, 2, 0, Math.PI * 2); ctx.fill(); } } else if (c.pat === 'grid') { ctx.lineWidth = 1; for (var x = 0; x <= W; x += sz) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); } for (var y = 0; y <= H; y += sz) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke(); } } else if (c.pat === 'stripe') { ctx.lineWidth = 2; for (var x = -H; x < W + H; x += sz) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x - H, H); ctx.stroke(); } } else if (c.pat === 'check') { for (var x = 0; x < W; x += sz)for (var y = 0; y < H; y += sz) { if ((Math.floor(x / sz) + Math.floor(y / sz)) % 2 === 0) ctx.fillRect(x, y, sz, sz); } } else if (c.pat === 'diamond') { ctx.lineWidth = 1; for (var x = 0; x < W; x += sz)for (var y = 0; y < H; y += sz) { ctx.beginPath(); ctx.moveTo(x + sz / 2, y); ctx.lineTo(x + sz, y + sz / 2); ctx.lineTo(x + sz / 2, y + sz); ctx.lineTo(x, y + sz / 2); ctx.closePath(); ctx.stroke(); } } else if (c.pat === 'zigzag') { ctx.lineWidth = 2; for (var y = 0; y < H; y += sz) { ctx.beginPath(); for (var x = 0; x < W; x += sz / 2) { var yo = (Math.floor(x / (sz / 2)) % 2 === 0) ? y : y + sz / 2; if (x === 0) ctx.moveTo(x, yo); else ctx.lineTo(x, yo); } ctx.stroke(); } } ctx.restore(); } }

/* ===== HISTORY ===== */
function serS() { return JSON.stringify({ els: els.map(function (e) { var c = {}; for (var k in e) c[k] = e[k]; if (e.type === 'image') { c.src = e.content.src; delete c.content; } if (e.eraserMask) { c.mask = e.eraserMask.toDataURL(); delete c.eraserMask; } return c; }), bgCf: bgCf }); }
function sH() { uS.push(serS()); if (uS.length > 40) uS.shift(); rS = []; }
function triggerUndo() { if (uS.length <= 1) return; rS.push(uS.pop()); restS(uS[uS.length - 1]); react('undo'); }
function triggerRedo() { if (!rS.length) return; var s = rS.pop(); uS.push(s); restS(s); react('redo'); }
function restS(json) { var p = JSON.parse(json); bgCf = p.bgCf || null; var ic = 0; for (var i = 0; i < p.els.length; i++)if (p.els[i].type === 'image') ic++; var ld = 0; els = p.els.map(function (e) { var o = {}; for (var k in e) o[k] = e[k]; if (e.type === 'image') { o.content = new Image(); o.content.crossOrigin = 'anonymous'; o.content.src = e.src || ''; o.content.onload = function () { ld++; if (ld >= ic) R(); }; o.eraserMask = document.createElement('canvas'); if (e.mask) { var mi = new Image(); mi.src = e.mask; mi.onload = function () { o.eraserMask.width = mi.width; o.eraserMask.height = mi.height; o.eraserMask.getContext('2d').drawImage(mi, 0, 0); }; } else { o.eraserMask.width = 400; o.eraserMask.height = 400; var mc = o.eraserMask.getContext('2d'); mc.fillStyle = '#fff'; mc.fillRect(0, 0, 400, 400); } } return o; }); selId = null; sUI(); if (!ic) R(); }

/* ===== LAYERS ===== */
function addText() { els.push({ id: 't' + Date.now(), type: 'text', text: 'EDIT TEXT', x: canvas.width / 2, y: canvas.height / 2, scale: 100, rotate: 0, opacity: 100, font: 'Arial', color: '#00f2fe', charSpacing: 0, curve: 0, stroke: 2, strokeColor: '#000000', emboss: 0, embossColor: '#ffffff', threeDDepth: 0, threeDColor: '#1e293b', threeDShadow: 0, threeDShadowColor: '#000000', innerShadow: 0, innerShadowColor: '#000000', reflection: 0, glow: 8, glowColor: '#00f2fe' }); selId = els[els.length - 1].id; sH(); R(); sUI(); react('added text'); }
function addImg(ev) { var f = ev.target.files[0]; if (f) loadI(f); ev.target.value = ''; }
function loadI(file) { var r = new FileReader(); r.readAsDataURL(file); r.onload = function (e) { var img = new Image(); img.src = e.target.result; img.onload = function () { var mc = document.createElement('canvas'); mc.width = img.width; mc.height = img.height; var mx = mc.getContext('2d'); mx.fillStyle = '#fff'; mx.fillRect(0, 0, mc.width, mc.height); var sc = 50; if (img.width * (sc / 100) > canvas.width * .6) sc = Math.floor(canvas.width * .6 / img.width * 100); if (img.height * (sc / 100) > canvas.height * .6) sc = Math.min(sc, Math.floor(canvas.height * .6 / img.height * 100)); sc = Math.max(12, sc); els.push({ id: 'i' + Date.now(), type: 'image', content: img, x: canvas.width / 2 - img.width * (sc / 100) / 2, y: canvas.height / 2 - img.height * (sc / 100) / 2, scale: sc, rotate: 0, opacity: 100, eraserMask: mc }); selId = els[els.length - 1].id; sH(); R(); sUI(); react('uploaded image'); }; }; }
function layerOp(a) { if (!selId) return; var i = -1; for (var j = 0; j < els.length; j++) { if (els[j].id === selId) { i = j; break; } } if (i === -1) return; if (a === 'del') { els.splice(i, 1); selId = null; react('deleted'); showSelBar(null); } else if (a === 'front') { els.push(els.splice(i, 1)[0]); } else if (a === 'back') { els.unshift(els.splice(i, 1)[0]); } else if (a === 'dup') { var s = els[i], c = {}; for (var k in s) c[k] = s[k]; c.id = 'd' + Date.now(); c.x = s.x + 12; c.y = s.y + 12; if (s.type === 'image' && s.eraserMask) { var nm = document.createElement('canvas'); nm.width = s.eraserMask.width; nm.height = s.eraserMask.height; nm.getContext('2d').drawImage(s.eraserMask, 0, 0); c.eraserMask = nm; c.content = s.content; } els.push(c); selId = c.id; react('duplicated'); } sH(); R(); sUI(); }
function alignEl(p) { var el = findEl(selId); if (!el) return; if (el.type === 'text') { if (p === 'l') el.x = 40; if (p === 'c') el.x = canvas.width / 2; if (p === 'r') el.x = canvas.width - 40; if (p === 'm') el.y = canvas.height / 2; } else { var w = el.content.width * (el.scale / 100), h = el.content.height * (el.scale / 100); if (p === 'l') el.x = 0; if (p === 'c') el.x = (canvas.width - w) / 2; if (p === 'r') el.x = canvas.width - w; if (p === 'm') el.y = (canvas.height - h) / 2; } sH(); R(); }

/* ===== CANVAS MOUSE ===== */
function gCC(e) { var r = canvas.getBoundingClientRect(); var ox = e.offsetX !== undefined ? e.offsetX : (e.clientX - r.left); var oy = e.offsetY !== undefined ? e.offsetY : (e.clientY - r.top); return { x: ox * (canvas.width / r.width), y: oy * (canvas.height / r.height) }; }
canvas.addEventListener('mousedown', mD); canvas.addEventListener('mousemove', mV); canvas.addEventListener('mouseup', mU); canvas.addEventListener('mouseleave', mU);
canvas.addEventListener('touchstart', function (e) { e.preventDefault(); var r = canvas.getBoundingClientRect(), t = e.touches[0]; mD({ offsetX: (t.clientX - r.left) * (canvas.width / r.width), offsetY: (t.clientY - r.top) * (canvas.height / r.height) }); }, { passive: false });
canvas.addEventListener('touchmove', function (e) { e.preventDefault(); var r = canvas.getBoundingClientRect(), t = e.touches[0]; mV({ offsetX: (t.clientX - r.left) * (canvas.width / r.width), offsetY: (t.clientY - r.top) * (canvas.height / r.height) }); }, { passive: false });
canvas.addEventListener('touchend', mU);

function mD(e) { var co = gCC(e), x = co.x, y = co.y; if (mode !== 'select') { drag = true; doErase(x, y); return; } var hit = null; for (var i = els.length - 1; i >= 0; i--) { if (hitEl(els[i], x, y)) { hit = els[i]; break; } } if (hit) { selId = hit.id; drag = true; dX = x - hit.x; dY = y - hit.y; sUI(); react('selected'); showSelBar(hit); } else { selId = null; sUI(); showSelBar(null); } R(); }
function hitEl(el, x, y) { if (el.type === 'image') { var w = el.content.width * (el.scale / 100), h = el.content.height * (el.scale / 100); return x >= el.x && x <= el.x + w && y >= el.y && y <= el.y + h; } if (el.type === 'text') { ctx.save(); ctx.font = 'bold ' + (el.scale * .6) + 'px "' + el.font + '"'; var tw = ctx.measureText(el.text || '').width; ctx.restore(); return x >= el.x - tw / 2 - 10 && x <= el.x + tw / 2 + 10 && y >= el.y - el.scale * .3 && y <= el.y + el.scale * .3; } return false; }
function mV(e) { var co = gCC(e), x = co.x, y = co.y; if (!drag) return; if (mode !== 'select') { doErase(x, y); return; } var el = findEl(selId); if (el) { el.x = x - dX; el.y = y - dY; R(); showSelBar(el); } }
function mU() { if (drag) sH(); drag = false; }
function setMode(m, btn) { mode = m; canvas.style.cursor = m !== 'select' ? 'crosshair' : 'default'; var btns = document.querySelectorAll('.mode-btn'); for (var i = 0; i < btns.length; i++)btns[i].classList.remove('active'); if (btn) btn.classList.add('active'); }
function doErase(cx, cy) { var el = findEl(selId); if (!el || el.type !== 'image') return; var mc = el.eraserMask.getContext('2d'), iw = el.content.width * (el.scale / 100), ih = el.content.height * (el.scale / 100); var rx = ((cx - el.x) / iw) * el.eraserMask.width, ry = ((cy - el.y) / ih) * el.eraserMask.height; var br = bSz * (el.eraserMask.width / Math.max(iw, 1)); mc.save(); mc.globalCompositeOperation = 'destination-out'; mc.fillStyle = 'rgba(0,0,0,1)'; mc.beginPath(); if (mode === 'mask') mc.rect(rx - br, ry - br, br * 2, br * 2); else mc.arc(rx, ry, br, 0, Math.PI * 2); mc.fill(); mc.restore(); R(); }
function restMask() { var el = findEl(selId); if (!el || el.type !== 'image') { alert('Select image!'); return; } var mc = el.eraserMask.getContext('2d'); mc.globalCompositeOperation = 'source-over'; mc.fillStyle = '#fff'; mc.fillRect(0, 0, el.eraserMask.width, el.eraserMask.height); sH(); R(); }

/* ===== PROPS ===== */
function setTxt(v) { var el = findEl(selId); if (el && el.type === 'text') { el.text = v; R(); } }
function setProp(p, v) { var el = findEl(selId); if (!el) return; var cp = ['color', 'strokeColor', 'threeDColor', 'glowColor', 'font', 'innerShadowColor', 'embossColor', 'threeDShadowColor']; el[p] = cp.indexOf(p) >= 0 ? v : parseFloat(v); var lm = { scale: ['v-sc', '%'], rotate: ['v-rt', ' deg'], opacity: ['v-op', '%'], charSpacing: ['v-sp', 'px'], curve: ['v-cu', ' deg'], stroke: ['v-st', 'px'], glow: ['v-gw', 'px'], threeDDepth: ['v-3d', 'px'], innerShadow: ['v-is', 'px'], emboss: ['v-em', 'px'], threeDShadow: ['v-3s', 'px'], reflection: ['v-rf', '%'] }; if (lm[p]) { var l = document.getElementById(lm[p][0]); if (l) l.innerText = v + lm[p][1]; var ml = document.getElementById('mob-' + lm[p][0]); if (ml) ml.innerText = v + lm[p][1]; } R(); }
function upFont(ev) { var f = ev.target.files[0]; if (!f) return; var r = new FileReader(); r.onload = function (e) { var n = f.name.replace(/\.[^/.]+$/, ''); try { var fc = new FontFace(n, 'url(' + e.target.result + ')'); fc.load().then(function (l) { document.fonts.add(l); var sel = document.getElementById('fontSel'); var op = document.createElement('option'); op.value = n; op.textContent = n; sel.appendChild(op); sel.value = n; react('font ' + n); }).catch(function (err) { alert('Font error: ' + err.message); }); } catch (err) { alert('Font load failed'); } }; r.readAsDataURL(f); ev.target.value = ''; }
function sV(id, v) { var e = document.getElementById(id); if (e) e.value = (v !== undefined && v !== null) ? v : 0; }
function sL(id, v, s) { var e = document.getElementById(id); if (e) e.innerText = ((v !== undefined && v !== null) ? v : 0) + s; }
function sUI() { var el = findEl(selId); var lb = document.getElementById('selLbl'); var lbd = document.getElementById('selLblDesk'); var name = el ? (el.type === 'text' ? '"' + (el.text || '').substring(0, 8) + '"' : 'Image') : 'None'; if (lb) lb.innerText = name; if (lbd) lbd.innerText = name; if (!el) { showSelBar(null); return; } sV('sl-sc', el.scale || 100); sL('v-sc', el.scale || 100, '%'); sV('sl-rt', el.rotate || 0); sL('v-rt', el.rotate || 0, ' deg'); sV('sl-op', el.opacity || 100); sL('v-op', el.opacity || 100, '%'); sV('mob-sl-sc', el.scale || 100); sL('mob-v-sc', el.scale || 100, '%'); sV('mob-sl-rt', el.rotate || 0); sL('mob-v-rt', el.rotate || 0, ' deg'); sV('mob-sl-op', el.opacity || 100); sL('mob-v-op', el.opacity || 100, '%'); if (el.type === 'text') { var ti = document.getElementById('txtIn'); if (ti) ti.value = el.text || ''; var mti = document.getElementById('mobTxtIn'); if (mti) mti.value = el.text || ''; var fs = document.getElementById('fontSel'); if (fs) { var opts = fs.querySelectorAll('option'); var has = false; for (var i = 0; i < opts.length; i++) { if (opts[i].value === el.font) has = true; } if (has) fs.value = el.font; } var tc = document.getElementById('txtCol'); if (tc) tc.value = el.color || '#00f2fe'; var mtc = document.getElementById('mobTxtCol'); if (mtc) mtc.value = el.color || '#00f2fe'; sV('sl-sp', el.charSpacing || 0); sL('v-sp', el.charSpacing || 0, 'px'); sV('sl-cu', el.curve || 0); sL('v-cu', el.curve || 0, ' deg'); sV('sl-st', el.stroke || 2); sL('v-st', el.stroke || 2, 'px'); var sc2 = document.getElementById('c-stroke'); if (sc2) sc2.value = el.strokeColor || '#000000'; sV('sl-gw', el.glow || 8); sL('v-gw', el.glow || 8, 'px'); var gc = document.getElementById('c-glow'); if (gc) gc.value = el.glowColor || '#00f2fe'; sV('sl-3d', el.threeDDepth || 0); sL('v-3d', el.threeDDepth || 0, 'px'); var td = document.getElementById('c-3d'); if (td) td.value = el.threeDColor || '#1e293b'; sV('sl-is', el.innerShadow || 0); sL('v-is', el.innerShadow || 0, 'px'); var isc = document.getElementById('c-is'); if (isc) isc.value = el.innerShadowColor || '#000000'; sV('sl-em', el.emboss || 0); sL('v-em', el.emboss || 0, 'px'); sV('sl-rf', el.reflection || 0); sL('v-rf', el.reflection || 0, '%'); } }

/* ===== TEXT RENDER ===== */
function dTxt(el) { ctx.save(); ctx.globalAlpha = el.opacity / 100; var fs = Math.max(el.scale * .6, 8); ctx.font = 'bold ' + fs + 'px "' + (el.font || 'Arial') + '"'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; var txt = el.text || '', sp = el.charSpacing || 0; function tw(s) { var w = 0; for (var i = 0; i < s.length; i++)w += ctx.measureText(s[i]).width + sp; return Math.max(w - sp, 1); } ctx.save(); ctx.translate(el.x, el.y); ctx.rotate((el.rotate || 0) * Math.PI / 180); if (el.curve && el.curve !== 0) { var ang = el.curve / 180 * Math.PI, al = tw(txt), rad = al / Math.abs(ang) || 300, ca = -Math.PI / 2 - ang / 2; for (var i = 0; i < txt.length; i++) { var ch = txt[i], cw = ctx.measureText(ch).width + sp, dA = cw / rad; ctx.save(); ctx.translate(Math.cos(ca + dA / 2) * rad, Math.sin(ca + dA / 2) * rad + (el.curve > 0 ? rad : -rad)); ctx.rotate(ca + dA / 2 + Math.PI / 2 + (el.curve > 0 ? 0 : Math.PI)); cFx(el, ch, 0, 0); ctx.restore(); ca += dA; } } else { var total = tw(txt), xO = -total / 2; for (var i = 0; i < txt.length; i++) { var ch = txt[i], cw = ctx.measureText(ch).width; cFx(el, ch, xO + cw / 2, 0); xO += cw + sp; } if ((el.reflection || 0) > 0) { ctx.save(); ctx.scale(1, -1); ctx.globalAlpha = el.reflection / 100 * .3; var rg = ctx.createLinearGradient(0, 0, 0, fs); rg.addColorStop(0, el.color || '#00f2fe'); rg.addColorStop(1, 'rgba(0,0,0,0)'); ctx.fillStyle = rg; var x2 = -total / 2; for (var i = 0; i < txt.length; i++) { var ch = txt[i], cw = ctx.measureText(ch).width; ctx.fillText(ch, x2 + cw / 2, -fs * .15); x2 += cw + sp; } ctx.restore(); } } ctx.restore(); ctx.restore(); }
function cFx(el, ch, x, y) { var d = el.threeDDepth || 0; if ((el.glow || 0) > 0) { ctx.save(); ctx.shadowColor = el.glowColor || '#00f2fe'; ctx.shadowBlur = el.glow; ctx.fillStyle = el.color || '#00f2fe'; ctx.fillText(ch, x, y); ctx.restore(); } if (d > 0) { ctx.fillStyle = el.threeDColor || '#1e293b'; for (var i = d; i >= 1; i--)ctx.fillText(ch, x + i * .8, y + i * .6); } if ((el.threeDShadow || 0) > 0) { ctx.save(); ctx.shadowColor = el.threeDShadowColor || 'rgba(0,0,0,.55)'; ctx.shadowBlur = el.threeDShadow; ctx.shadowOffsetX = d * .5; ctx.shadowOffsetY = d * .5; ctx.fillStyle = el.color || '#00f2fe'; ctx.fillText(ch, x, y); ctx.restore(); } if ((el.emboss || 0) > 0) { ctx.save(); ctx.fillStyle = el.embossColor || 'rgba(255,255,255,.3)'; ctx.globalAlpha = .3; ctx.fillText(ch, x - el.emboss * .4, y - el.emboss * .4); ctx.fillStyle = 'rgba(0,0,0,.3)'; ctx.fillText(ch, x + el.emboss * .4, y + el.emboss * .4); ctx.restore(); } if ((el.innerShadow || 0) > 0) { ctx.save(); ctx.shadowColor = el.innerShadowColor || 'rgba(0,0,0,.7)'; ctx.shadowBlur = el.innerShadow; ctx.shadowOffsetX = 2; ctx.shadowOffsetY = 2; ctx.fillStyle = el.color || '#00f2fe'; ctx.fillText(ch, x, y); ctx.restore(); } if ((el.stroke || 0) > 0) { ctx.save(); ctx.lineWidth = el.stroke; ctx.strokeStyle = el.strokeColor || '#000'; ctx.lineJoin = 'round'; ctx.strokeText(ch, x, y); ctx.restore(); } ctx.fillStyle = el.color || '#00f2fe'; ctx.fillText(ch, x, y); }

/* ===== RENDER ===== */
function R() { ctx.clearRect(0, 0, canvas.width, canvas.height); paintBg(); for (var i = 0; i < els.length; i++) { var el = els[i]; ctx.save(); ctx.globalAlpha = (el.opacity || 100) / 100; if (el.type === 'image') { if (!el.content || !el.content.complete || !el.content.naturalWidth) { ctx.restore(); continue; } var w = el.content.width * (el.scale / 100), h = el.content.height * (el.scale / 100); if (w <= 0 || h <= 0) { ctx.restore(); continue; } ctx.translate(el.x + w / 2, el.y + h / 2); ctx.rotate((el.rotate || 0) * Math.PI / 180); var tmp = document.createElement('canvas'); tmp.width = w; tmp.height = h; var tx = tmp.getContext('2d'); tx.drawImage(el.content, 0, 0, w, h); if (el.eraserMask) { tx.globalCompositeOperation = 'destination-in'; tx.drawImage(el.eraserMask, 0, 0, w, h); } ctx.drawImage(tmp, -w / 2, -h / 2); } else if (el.type === 'text') { dTxt(el); } ctx.restore(); } }

/* ===== GRADING ===== */
function liveG() { var ids = ['br', 'ct', 'sa', 'te', 'vi', 'gr']; for (var i = 0; i < ids.length; i++) { var s = document.getElementById('sg-' + ids[i]) || document.getElementById('mob-sg-' + ids[i]); var v = document.getElementById('vg-' + ids[i]); if (s && v) v.innerText = s.value; } }
var gPD = { cinematic: { br: -10, ct: 30, sa: -15, te: 10, vi: 40, gr: 5 }, vintage: { br: 5, ct: 10, sa: -30, te: 15, vi: 30, gr: 15 }, warm: { br: 10, ct: 10, sa: 15, te: 30, vi: 10, gr: 0 }, cool: { br: 0, ct: 15, sa: -10, te: -30, vi: 15, gr: 0 }, noir: { br: -20, ct: 50, sa: -100, te: 0, vi: 60, gr: 10 }, neon: { br: 0, ct: 40, sa: 50, te: -10, vi: 20, gr: 0 }, sepia: { br: 10, ct: 10, sa: -60, te: 30, vi: 20, gr: 8 }, golden: { br: 10, ct: 20, sa: 20, te: 35, vi: 15, gr: 0 }, hdr: { br: 5, ct: 50, sa: 30, te: 0, vi: 10, gr: 0 } };
function gradeP(n) { var p = gPD[n]; if (!p) return; for (var k in p) { var sl = document.getElementById('sg-' + k); if (sl) sl.value = p[k]; var msl = document.getElementById('mob-sg-' + k); if (msl) msl.value = p[k]; } liveG(); }
function resetGrade() { var ids = ['br', 'ct', 'sa', 'te', 'vi', 'gr']; for (var i = 0; i < ids.length; i++) { var sl = document.getElementById('sg-' + ids[i]); if (sl) sl.value = 0; var msl = document.getElementById('mob-sg-' + ids[i]); if (msl) msl.value = 0; } liveG(); }
function applyGrade() { R(); try { var d = ctx.getImageData(0, 0, canvas.width, canvas.height), px = d.data; var br = parseInt((document.getElementById('sg-br') || document.getElementById('mob-sg-br') || { value: 0 }).value) || 0; var ct = parseInt((document.getElementById('sg-ct') || document.getElementById('mob-sg-ct') || { value: 0 }).value) || 0; var sa = parseInt((document.getElementById('sg-sa') || document.getElementById('mob-sg-sa') || { value: 0 }).value) || 0; var te = parseInt((document.getElementById('sg-te') || document.getElementById('mob-sg-te') || { value: 0 }).value) || 0; var vi = parseInt((document.getElementById('sg-vi') || document.getElementById('mob-sg-vi') || { value: 0 }).value) || 0; var gr = parseInt((document.getElementById('sg-gr') || document.getElementById('mob-sg-gr') || { value: 0 }).value) || 0; var cf = (259 * (ct + 255)) / (255 * (259 - ct)); for (var i = 0; i < px.length; i += 4) { var r = px[i], g = px[i + 1], b = px[i + 2]; r += br; g += br; b += br; r = cf * (r - 128) + 128; g = cf * (g - 128) + 128; b = cf * (b - 128) + 128; r += te; b -= te; var gray = .299 * r + .587 * g + .114 * b, sf = 1 + sa / 100; r = gray + sf * (r - gray); g = gray + sf * (g - gray); b = gray + sf * (b - gray); px[i] = Math.max(0, Math.min(255, r)); px[i + 1] = Math.max(0, Math.min(255, g)); px[i + 2] = Math.max(0, Math.min(255, b)); } if (vi > 0) { var W = canvas.width, H = canvas.height, cx = W / 2, cy = H / 2, mD = Math.sqrt(cx * cx + cy * cy); for (var y = 0; y < H; y++)for (var x = 0; x < W; x++) { var dist = Math.sqrt((x - cx) * (x - cx) + (y - cy) * (y - cy)) / mD, f = 1 - dist * dist * (vi / 100) * 1.5, idx = (y * W + x) * 4; px[idx] *= f; px[idx + 1] *= f; px[idx + 2] *= f; } } if (gr > 0) { for (var i = 0; i < px.length; i += 4) { var n = (Math.random() - .5) * gr * 3; px[i] = Math.max(0, Math.min(255, px[i] + n)); px[i + 1] = Math.max(0, Math.min(255, px[i + 1] + n)); px[i + 2] = Math.max(0, Math.min(255, px[i + 2] + n)); } } ctx.putImageData(d, 0, 0); var img = new Image(); img.src = canvas.toDataURL(); img.onload = function () { aiBg = img; bgCf = null; sH(); R(); }; react('grade applied'); } catch (e) { react('grade error'); } }

/* ===== PIXART ===== */
function getD() { R(); return ctx.getImageData(0, 0, canvas.width, canvas.height); }
function apD(d) { ctx.putImageData(d, 0, 0); var img = new Image(); img.src = canvas.toDataURL(); img.onload = function () { aiBg = img; bgCf = null; sH(); R(); }; react('effect applied'); }
function pixelate(sz) { R(); var W = canvas.width, H = canvas.height, d = ctx.getImageData(0, 0, W, H), px = d.data; for (var y = 0; y < H; y += sz)for (var x = 0; x < W; x += sz) { var r = 0, g = 0, b = 0, c = 0; for (var dy = 0; dy < sz && y + dy < H; dy++)for (var dx = 0; dx < sz && x + dx < W; dx++) { var i = ((y + dy) * W + (x + dx)) * 4; r += px[i]; g += px[i + 1]; b += px[i + 2]; c++; } r /= c; g /= c; b /= c; for (var dy = 0; dy < sz && y + dy < H; dy++)for (var dx = 0; dx < sz && x + dx < W; dx++) { var i = ((y + dy) * W + (x + dx)) * 4; px[i] = r; px[i + 1] = g; px[i + 2] = b; } } apD(d); }
function applyBlur(rad) { R(); var W = canvas.width, H = canvas.height, src = ctx.getImageData(0, 0, W, H), dst = ctx.createImageData(W, H), s = src.data, d = dst.data; for (var y = 0; y < H; y++)for (var x = 0; x < W; x++) { var r = 0, g = 0, b = 0, c = 0; for (var dy = -rad; dy <= rad; dy++)for (var dx = -rad; dx <= rad; dx++) { var nx = x + dx, ny = y + dy; if (nx >= 0 && nx < W && ny >= 0 && ny < H) { var i = (ny * W + nx) * 4; r += s[i]; g += s[i + 1]; b += s[i + 2]; c++; } } var i = (y * W + x) * 4; d[i] = r / c; d[i + 1] = g / c; d[i + 2] = b / c; d[i + 3] = s[i + 3]; } apD(dst); }
function applySharpen() { R(); var W = canvas.width, H = canvas.height, src = ctx.getImageData(0, 0, W, H), dst = ctx.createImageData(W, H), s = src.data, d = dst.data; var k = [0, -1, 0, -1, 5, -1, 0, -1, 0]; for (var y = 1; y < H - 1; y++)for (var x = 1; x < W - 1; x++) { var r = 0, g = 0, b = 0, ki = 0; for (var dy = -1; dy <= 1; dy++)for (var dx = -1; dx <= 1; dx++) { var i = ((y + dy) * W + (x + dx)) * 4; r += s[i] * k[ki]; g += s[i + 1] * k[ki]; b += s[i + 2] * k[ki]; ki++; } var i = (y * W + x) * 4; d[i] = Math.max(0, Math.min(255, r)); d[i + 1] = Math.max(0, Math.min(255, g)); d[i + 2] = Math.max(0, Math.min(255, b)); d[i + 3] = s[i + 3]; } apD(dst); }
function invertColors() { var d = getD(), px = d.data; for (var i = 0; i < px.length; i += 4) { px[i] = 255 - px[i]; px[i + 1] = 255 - px[i + 1]; px[i + 2] = 255 - px[i + 2]; } apD(d); }
function grayscale() { var d = getD(), px = d.data; for (var i = 0; i < px.length; i += 4) { var g = .299 * px[i] + .587 * px[i + 1] + .114 * px[i + 2]; px[i] = px[i + 1] = px[i + 2] = g; } apD(d); }
function posterize(lv) { var d = getD(), px = d.data, step = 255 / lv; for (var i = 0; i < px.length; i += 4) { px[i] = Math.round(px[i] / step) * step; px[i + 1] = Math.round(px[i + 1] / step) * step; px[i + 2] = Math.round(px[i + 2] / step) * step; } apD(d); }
function edgeDetect() { R(); var W = canvas.width, H = canvas.height, src = ctx.getImageData(0, 0, W, H), dst = ctx.createImageData(W, H), s = src.data, d = dst.data; for (var y = 1; y < H - 1; y++)for (var x = 1; x < W - 1; x++) { var i = (y * W + x) * 4; var gx = (-s[((y - 1) * W + x - 1) * 4] + s[((y - 1) * W + x + 1) * 4] - 2 * s[(y * W + x - 1) * 4] + 2 * s[(y * W + x + 1) * 4] - s[((y + 1) * W + x - 1) * 4] + s[((y + 1) * W + x + 1) * 4]); var gy = (-s[((y - 1) * W + x - 1) * 4] - 2 * s[((y - 1) * W + x) * 4] - s[((y - 1) * W + x + 1) * 4] + s[((y + 1) * W + x - 1) * 4] + 2 * s[((y + 1) * W + x) * 4] + s[((y + 1) * W + x + 1) * 4]); d[i] = d[i + 1] = d[i + 2] = Math.min(255, Math.sqrt(gx * gx + gy * gy)); d[i + 3] = 255; } apD(dst); }
function applyNoise(amt) { var d = getD(), px = d.data; for (var i = 0; i < px.length; i += 4) { var n = (Math.random() - .5) * amt * 2; px[i] = Math.max(0, Math.min(255, px[i] + n)); px[i + 1] = Math.max(0, Math.min(255, px[i + 1] + n)); px[i + 2] = Math.max(0, Math.min(255, px[i + 2] + n)); } apD(d); }
function flipH() { R(); var W = canvas.width, H = canvas.height, d = ctx.getImageData(0, 0, W, H), px = d.data; for (var y = 0; y < H; y++)for (var x = 0; x < Math.floor(W / 2); x++) { var l = (y * W + x) * 4, r = (y * W + (W - 1 - x)) * 4; for (var c = 0; c < 4; c++) { var tmp = px[l + c]; px[l + c] = px[r + c]; px[r + c] = tmp; } } apD(d); }

/* ===== AI BG REMOVE ===== */
function bgRemove(method) { var el = findEl(selId); if (!el || el.type !== 'image') { alert('Select image!'); return; } react('removing bg'); loader.style.display = 'flex'; document.getElementById('ldrMsg').innerText = 'Removing...'; var tol = parseInt((document.getElementById('sl-tol') || { value: 50 }).value) || 50; setTimeout(function () { try { var mc = el.eraserMask, mx = mc.getContext('2d'); var tc = document.createElement('canvas'); tc.width = el.content.width; tc.height = el.content.height; tc.getContext('2d').drawImage(el.content, 0, 0); var d; try { d = tc.getContext('2d').getImageData(0, 0, tc.width, tc.height); } catch (e) { loader.style.display = 'none'; alert('CORS error'); return; } var data = d.data, W = tc.width, H = tc.height; mx.globalCompositeOperation = 'source-over'; mx.fillStyle = '#fff'; mx.fillRect(0, 0, mc.width, mc.height); var md = mx.getImageData(0, 0, mc.width, mc.height), mD = md.data, scX = mc.width / W, scY = mc.height / H; function mark(px, py) { var mx2 = Math.round(px * scX), my2 = Math.round(py * scY); if (mx2 >= 0 && mx2 < mc.width && my2 >= 0 && my2 < mc.height) { var mi = (my2 * mc.width + mx2) * 4; mD[mi] = mD[mi + 1] = mD[mi + 2] = mD[mi + 3] = 0; } } if (method === 'color' || method === 'smart') { var corners = [[0, 0], [W - 1, 0], [0, H - 1], [W - 1, H - 1]], tR = 0, tG = 0, tB = 0; for (var ci = 0; ci < corners.length; ci++) { var idx = (corners[ci][1] * W + corners[ci][0]) * 4; tR += data[idx]; tG += data[idx + 1]; tB += data[idx + 2]; } tR /= 4; tG /= 4; tB /= 4; for (var py = 0; py < H; py++)for (var px = 0; px < W; px++) { var si = (py * W + px) * 4; if (Math.sqrt(Math.pow(data[si] - tR, 2) + Math.pow(data[si + 1] - tG, 2) + Math.pow(data[si + 2] - tB, 2)) < tol) mark(px, py); } } if (method === 'bright' || method === 'smart') { for (var py = 0; py < H; py++)for (var px = 0; px < W; px++) { var si = (py * W + px) * 4, b = (data[si] + data[si + 1] + data[si + 2]) / 3; if (b > 255 - tol / 2 || b < tol / 2) mark(px, py); } } if (method === 'edge' || method === 'smart') { var vis = new Uint8Array(W * H), starts = [[0, 0], [W - 1, 0], [0, H - 1], [W - 1, H - 1]]; for (var si2 = 0; si2 < starts.length; si2++) { var stk = [starts[si2]], ri = (starts[si2][1] * W + starts[si2][0]) * 4, rR = data[ri], rG = data[ri + 1], rB = data[ri + 2]; while (stk.length) { var pt = stk.pop(), cx2 = pt[0], cy2 = pt[1]; if (cx2 < 0 || cx2 >= W || cy2 < 0 || cy2 >= H) continue; var idx2 = cy2 * W + cx2; if (vis[idx2]) continue; vis[idx2] = 1; var pi = idx2 * 4; if (Math.sqrt(Math.pow(data[pi] - rR, 2) + Math.pow(data[pi + 1] - rG, 2) + Math.pow(data[pi + 2] - rB, 2)) < tol) { mark(cx2, cy2); if (stk.length < 500000) stk.push([cx2 + 1, cy2], [cx2 - 1, cy2], [cx2, cy2 + 1], [cx2, cy2 - 1]); } } } } mx.putImageData(md, 0, 0); sH(); R(); react('bg removed'); } catch (e) { react('bg remove error'); } finally { loader.style.display = 'none'; } }, 400); }

/* ===== AI GENERATE ===== */
function generateAI() { var pv = (document.getElementById('aiPrompt').value || '').trim(); if (!pv) { alert('Enter prompt!'); return; } loader.style.display = 'flex'; document.getElementById('ldrMsg').innerText = 'Generating...'; react('generating AI'); var style = document.getElementById('aiStyle').value || ''; var aiMode = document.getElementById('aiMode').value || 'bg'; var url = 'https://image.pollinations.ai/prompt/' + encodeURIComponent(pv + style) + '?width=' + canvas.width + '&height=' + canvas.height + '&nologo=true&seed=' + Math.floor(Math.random() * 99999); var nb = new Image(); nb.crossOrigin = 'anonymous'; var to = setTimeout(function () { loader.style.display = 'none'; react('timeout'); }, 45000); nb.onload = function () { clearTimeout(to); loader.style.display = 'none'; if (aiMode === 'bg') { aiBg = nb; bgCf = null; sH(); R(); react('AI bg done'); } else { var mc = document.createElement('canvas'); mc.width = nb.width; mc.height = nb.height; var mx = mc.getContext('2d'); mx.fillStyle = '#fff'; mx.fillRect(0, 0, mc.width, mc.height); var sc = 50; if (nb.width * (sc / 100) > canvas.width * .6) sc = Math.floor(canvas.width * .6 / nb.width * 100); sc = Math.max(12, sc); els.push({ id: 'ai' + Date.now(), type: 'image', content: nb, x: canvas.width / 2 - nb.width * (sc / 100) / 2, y: canvas.height / 2 - nb.height * (sc / 100) / 2, scale: sc, rotate: 0, opacity: 100, eraserMask: mc }); selId = els[els.length - 1].id; sH(); R(); sUI(); react('AI layer done'); } }; nb.onerror = function () { clearTimeout(to); loader.style.display = 'none'; react('AI failed'); }; nb.src = url; }

/* ===== MISC ===== */
function resetAll() { if (!confirm('Reset everything?')) return; els = []; selId = null; aiBg = null; bgCf = null; uS = []; rS = []; sUI(); R(); react('reset'); }
function exportHD() { try { var link = document.createElement('a'); link.download = 'Arjona_' + Date.now() + '.png'; link.href = canvas.toDataURL('image/png', 1.0); link.click(); react('exported'); } catch (e) { react('export error'); alert('Export failed (CORS): ' + e.message); } }
function doVoice(ev) { ev.preventDefault(); var SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) { alert('Speech not supported'); return; } var rec = new SR(); rec.lang = 'en-US'; var btn = ev.target; if (btn) btn.innerText = '...'; rec.onresult = function (e) { var t = e.results[0][0].transcript; document.getElementById('aiPrompt').value = t; react('voice: ' + t); }; rec.onend = function () { if (btn) btn.innerText = 'Mic'; }; rec.onerror = function () { if (btn) btn.innerText = 'Mic'; }; rec.start(); }

/* ===== KEYBOARD ===== */
document.addEventListener('keydown', function (e) { var t = document.activeElement ? document.activeElement.tagName : ''; if (t === 'INPUT' || t === 'TEXTAREA' || t === 'SELECT') return; if (e.key === 'Escape') { closeHelp(); closeBottomSheet(); closeMobMenu(); } if ((e.key === 'Delete' || e.key === 'Backspace') && selId) layerOp('del'); if ((e.ctrlKey || e.metaKey) && !e.shiftKey && e.key === 'z') { e.preventDefault(); triggerUndo(); } if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === 'z') { e.preventDefault(); triggerRedo(); } if ((e.ctrlKey || e.metaKey) && e.key === 'd') { e.preventDefault(); if (selId) layerOp('dup'); } if ((e.ctrlKey || e.metaKey) && e.key === 's') { e.preventDefault(); exportHD(); } if (selId && ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].indexOf(e.key) >= 0) { e.preventDefault(); var el = findEl(selId); var st = e.shiftKey ? 10 : 2; if (el) { if (e.key === 'ArrowUp') el.y -= st; if (e.key === 'ArrowDown') el.y += st; if (e.key === 'ArrowLeft') el.x -= st; if (e.key === 'ArrowRight') el.x += st; R(); showSelBar(el); } } });

/* ===== DRAG DROP ===== */
window.addEventListener('dragover', function (e) { e.preventDefault(); });
window.addEventListener('drop', function (e) { e.preventDefault(); var files = e.dataTransfer.files; for (var i = 0; i < files.length; i++) { if (files[i].type.indexOf('image/') === 0) loadI(files[i]); } });

/* ===== INIT ===== */
window.addEventListener('DOMContentLoaded', function () {
    initTheme();

    var rL = document.getElementById('resizeLeft'), rB = document.getElementById('resizeBottom');
    var lSb = document.getElementById('leftSidebar'), bPn = document.getElementById('bottomPanel');

    if (rL && lSb) { rL.addEventListener('mousedown', function (e) { e.preventDefault(); e.stopPropagation(); resLOn = true; resLX = e.clientX; resLW = lSb.getBoundingClientRect().width; document.body.style.userSelect = 'none'; document.body.style.cursor = 'col-resize'; rL.style.background = 'var(--ac)'; }); rL.addEventListener('touchstart', function (e) { e.preventDefault(); resLOn = true; resLX = e.touches[0].clientX; resLW = lSb.getBoundingClientRect().width; }, { passive: false }); }
    if (rB && bPn) { rB.addEventListener('mousedown', function (e) { e.preventDefault(); e.stopPropagation(); resBOn = true; resBY = e.clientY; resBH = bPn.getBoundingClientRect().height; document.body.style.userSelect = 'none'; document.body.style.cursor = 'row-resize'; rB.style.background = 'var(--ac)'; }); rB.addEventListener('touchstart', function (e) { e.preventDefault(); resBOn = true; resBY = e.touches[0].clientY; resBH = bPn.getBoundingClientRect().height; }, { passive: false }); }

    var corners = ['rhNW', 'rhNE', 'rhSW', 'rhSE'];
    for (var ci = 0; ci < corners.length; ci++) { (function (cid) { var ch = document.getElementById(cid); if (ch) { ch.addEventListener('mousedown', function (e) { initCornerResize(cid, e); }); ch.addEventListener('touchstart', function (e) { e.preventDefault(); initCornerResize(cid, { clientX: e.touches[0].clientX, clientY: e.touches[0].clientY, preventDefault: function () { }, stopPropagation: function () { } }); }, { passive: false }); } })(corners[ci]); }

    document.addEventListener('mousemove', function (e) {
        if (resLOn && lSb) { var nw = Math.max(140, Math.min(400, resLW + (e.clientX - resLX))); lSb.style.width = nw + 'px'; lSb.style.minWidth = nw + 'px'; lSb.style.maxWidth = nw + 'px'; }
        if (resBOn && bPn) { var nh = Math.max(44, Math.min(window.innerHeight * 0.6, resBH - (e.clientY - resBY))); bPn.style.height = nh + 'px'; bPn.style.minHeight = nh + 'px'; bPn.style.maxHeight = nh + 'px'; }
        if (cornerDrag) { var el = findEl(selId); if (el) { var dx = e.clientX - cornerStartX; var delta = (cornerDrag.indexOf('NW') >= 0 || cornerDrag.indexOf('SW') >= 0) ? -dx : dx; if (e.shiftKey) delta = Math.max(Math.abs(dx), Math.abs(e.clientY - cornerStartY)) * (dx >= 0 ? 1 : -1); var ns = Math.max(12, Math.min(320, cornerStartScale + delta * 0.35)); el.scale = Math.round(ns); R(); showCornerHandles(el); showSelBar(el); sUI(); } }
    });

    document.addEventListener('mouseup', function () {
        if (resLOn) { resLOn = false; document.body.style.userSelect = ''; document.body.style.cursor = ''; if (rL) rL.style.background = ''; }
        if (resBOn) { resBOn = false; document.body.style.userSelect = ''; document.body.style.cursor = ''; if (rB) rB.style.background = ''; }
        if (cornerDrag) { cornerDrag = null; document.body.style.userSelect = ''; sH(); }
    });

    document.addEventListener('touchmove', function (e) {
        if (resLOn && lSb) { var nw = Math.max(140, Math.min(400, resLW + (e.touches[0].clientX - resLX))); lSb.style.width = nw + 'px'; lSb.style.minWidth = nw + 'px'; lSb.style.maxWidth = nw + 'px'; }
        if (resBOn && bPn) { var nh = Math.max(44, Math.min(window.innerHeight * 0.6, resBH - (e.touches[0].clientY - resBY))); bPn.style.height = nh + 'px'; bPn.style.minHeight = nh + 'px'; bPn.style.maxHeight = nh + 'px'; }
        if (cornerDrag) { var el = findEl(selId); if (el) { var dx = e.touches[0].clientX - cornerStartX; var ns = Math.max(12, Math.min(320, cornerStartScale + dx * 0.35)); el.scale = Math.round(ns); R(); showCornerHandles(el); } }
    }, { passive: false });

    document.addEventListener('touchend', function () {
        if (resLOn) { resLOn = false; if (rL) rL.style.background = ''; }
        if (resBOn) { resBOn = false; if (rB) rB.style.background = ''; }
        if (cornerDrag) { cornerDrag = null; sH(); }
    });

    setupC(1280, 720);
    sH();
    askAI('user opened Arjona AI Studio', false);
});